apiVersion: v1
kind: Pod
metadata:
  name: frontend
  namespace: aws-simulation
  labels:
    app: frontend
spec:
  containers:
    - name: frontend
      image: nginx:alpine
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: aws-simulation
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: backend
  namespace: aws-simulation
  labels:
    app: backend
spec:
  containers:
    - name: backend
      image: hashicorp/http-echo
      args:
        - "-text=aws-simulation backend up"
      ports:
        - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: aws-simulation
spec:
  selector:
    app: backend
  ports:
    - port: 5678
      targetPort: 5678
